name: Build EOQ Pro
on: [workflow_dispatch, push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PyInstaller
        run: python -m pip install --upgrade pip pyinstaller

      - name: Build app
        shell: bash
        run: |
          ADD_DATA=""
          [ -f brand_logo.svg ] && ADD_DATA="--add-data brand_logo.svg:."
          ICON=""
          if [ "$RUNNER_OS" = "Windows" ] && [ -f app.ico ]; then ICON='--icon app.ico'; fi
          if [ "$RUNNER_OS" = "macOS" ] && [ -f app.icns ]; then ICON='--icon app.icns'; fi
          python -m PyInstaller --noconsole --onefile --name EOQ_Pro $ADD_DATA $ICON eoq_pro.py

      - name: Package per OS
        shell: bash
        run: |
          mkdir EOQ_Pro_Demo
          cp eoq_pro.py EOQ_Pro_Demo/ || true
          [ -f Guida_EOQ_Pro_Semplice_compact.pdf ] && cp Guida_EOQ_Pro_Semplice_compact.pdf EOQ_Pro_Demo/Guida_EOQ_Pro.pdf
          [ -f Guida_EOQ_Pro_Semplice.txt ] && cp Guida_EOQ_Pro_Semplice.txt EOQ_Pro_Demo/Guida_EOQ_Pro.txt
          [ -f EULA.txt ] && cp EULA.txt EOQ_Pro_Demo/
          [ -f Privacy_Policy.txt ] && cp Privacy_Policy.txt EOQ_Pro_Demo/
          [ -f eoq_demo_sample.csv ] && cp eoq_demo_sample.csv EOQ_Pro_Demo/

          if [ "$RUNNER_OS" = "Windows" ]; then
            cp dist/EOQ_Pro.exe EOQ_Pro_Demo/
            pwsh -NoProfile -Command "Compress-Archive -Path 'EOQ_Pro_Demo\\*' -DestinationPath 'eoq_pro_windows.zip' -Force"
          elif [ "$RUNNER_OS" = "macOS" ]; then
            # Se hai creato una app .app con --onefile, PyInstaller su mac fa un binario; per una .app usa --windowed (facoltativo).
            cp dist/EOQ_Pro EOQ_Pro_Demo/ 2>/dev/null || true
            # In alternativa, se generi una .app: cp -R dist/EOQ_Pro.app EOQ_Pro_Demo/
            ditto -c -k --sequesterRsrc --keepParent "EOQ_Pro_Demo" "eoq_pro_macos.zip"
          else
            cp dist/EOQ_Pro EOQ_Pro_Demo/
            zip -r eoq_pro_linux.zip EOQ_Pro_Demo >/dev/null
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: |
            eoq_pro_windows.zip
            eoq_pro_macos.zip
            eoq_pro_linux.zip
          if-no-files-found: ignore
